#include "main.h"

// Function prototypes
void SystemClock_Config(void);
void MX_GPIO_Init(void);

// Define LED and buzzer pins
#define LED1_PIN GPIO_PIN_7 // PC7
#define LED2_PIN GPIO_PIN_6 // PB6
#define LED3_PIN GPIO_PIN_7 // PA7
#define LED4_PIN GPIO_PIN_6 // PA6
#define LED5_PIN GPIO_PIN_5 // PA5
#define BUZZER_PIN GPIO_PIN_1 // PA1
#define INPUT_PIN GPIO_PIN_0 // PA0

#define LED1_PORT GPIOC
#define LED2_PORT GPIOB
#define LED3_PORT GPIOA
#define LED4_PORT GPIOA
#define LED5_PORT GPIOA
#define BUZZER_PORT GPIOA
#define INPUT_PORT GPIOA

int main(void) {
    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();

    while (1) {
        // Check if PA0 receives HIGH
        if (HAL_GPIO_ReadPin(INPUT_PORT, INPUT_PIN) == GPI8O_PIN_SET) {
            // Flash all LEDs rapidly
            // Buzz 5 times with a 3-second interval
            for (int i = 0; i < 25; i++) {
                HAL_GPIO_WritePin(BUZZER_PORT, BUZZER_PIN, GPIO_PIN_SET); // Turn buzzer on
                HAL_Delay(100); // Buzzer ON for 500ms
                HAL_GPIO_WritePin(BUZZER_PORT, BUZZER_PIN, GPIO_PIN_RESET); // Turn buzzer off
                HAL_Delay(100); // Delay 2.5 seconds before next buzz
            }
        }
    }
}

// GPIO Initialization Function
void MX_GPIO_Init(void) {
    GPIO_InitTypeDef GPIO_InitStruct = {0};

    // Enable GPIO Clocks
    __HAL_RCC_GPIOA_CLK_ENABLE();
    __HAL_RCC_GPIOB_CLK_ENABLE();
    __HAL_RCC_GPIOC_CLK_ENABLE();

    // Configure PA0 as Input with Pull-Down (Input signal)
    GPIO_InitStruct.Pin = INPUT_PIN;
    GPIO_InitStruct.Mode = GPIO_MODE_INPUT;
    GPIO_InitStruct.Pull = GPIO_PULLDOWN;
    HAL_GPIO_Init(INPUT_PORT, &GPIO_InitStruct);

    // Configure LEDs as Output
    GPIO_InitStruct.Pin = LED1_PIN;
    GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(LED1_PORT, &GPIO_InitStruct);

    GPIO_InitStruct.Pin = LED2_PIN;
    HAL_GPIO_Init(LED2_PORT, &GPIO_InitStruct);

    GPIO_InitStruct.Pin = LED3_PIN | LED4_PIN | LED5_PIN;
    HAL_GPIO_Init(LED3_PORT, &GPIO_InitStruct);

    // Configure PA1 as Output for Buzzer
    GPIO_InitStruct.Pin = BUZZER_PIN;
    GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(BUZZER_PORT, &GPIO_InitStruct);
}

// System Clock Configuration
void SystemClock_Config(void) {
    // System clock setup generated by STM32CubeMX
    // Ensure proper clock configuration for GPIO operations
}
